import type { Edge, Node } from "@xyflow/react";
import type { FlowScenario, RunbookNodeData } from "../types";
import { layoutNodes } from "./layout";

function n(
  id: string,
  title: string,
  subtitle: string,
  stereotype: RunbookNodeData["stereotype"],
  notes?: string,
): Node<RunbookNodeData> {
  return {
    id,
    type: "runbook",
    position: { x: 0, y: 0 },
    data: { title, subtitle, stereotype, notes },
  };
}

function e(
  id: string,
  source: string,
  target: string,
  label?: string,
  animated = false,
): Edge {
  return {
    id,
    source,
    target,
    label,
    animated,
    type: "smoothstep",
    markerEnd: { type: "arrowclosed" },
  };
}

function buildScenario(base: Omit<FlowScenario, "nodes"> & { nodes: Node<RunbookNodeData>[] }): FlowScenario {
  return {
    ...base,
    nodes: layoutNodes(base.nodes, base.edges, "TB"),
  };
}

const k8sIncident = buildScenario({
  id: "k8s-incident",
  name: "K8s Incident Response",
  archetype: "mitigation",
  summary:
    "Wait-for-event trigger, parallel diagnostics, conditional remediation branches, and explicit decision routing.",
  nodes: [
    n("alert", "Wait for Alert", "type: wait_for_event", "trigger", "prometheus.alert.firing"),
    n("diag", "Gather Diagnostics", "type: parallel", "control", "manifest + describe + logs"),
    n("analyze", "Analyze Failure", "type: branch", "control"),
    n("approval", "SRE Approval", "type: decision", "decision", "approve / reject / escalate"),
    n("approval_reject", "Stop: Rejected", "type: end", "terminal", "manual rejection"),
    n("approval_escalate", "Escalate to SRE Senior", "type: end", "terminal", "approval timeout/escalation"),
    n("remediate", "Apply Fix", "type: cli", "automation", "kubectl apply/patch"),
    n("verify", "Verify Recovery", "type: cli + retry", "automation"),
    n("notify", "Notify Stakeholders", "type: tool", "automation", "slack + pagerduty"),
    n("done", "End", "type: end", "terminal"),
  ],
  edges: [
    e("e1", "alert", "diag"),
    e("e2", "diag", "analyze"),
    e("e3", "analyze", "approval", "config/oom branch"),
    e("e4", "approval", "remediate", "approved"),
    e("e4b", "approval", "approval_reject", "rejected"),
    e("e4c", "approval", "approval_escalate", "escalated"),
    e("e5", "remediate", "verify"),
    e("e6", "verify", "notify"),
    e("e7", "notify", "done"),
  ],
});

const onboarding = buildScenario({
  id: "employee-onboarding",
  name: "Employee Onboarding",
  archetype: "reference",
  summary:
    "Human-heavy flow with explicit decision outcomes and broad parallel provisioning branches.",
  nodes: [
    n("collect", "Collect Employee Data", "type: collector", "human"),
    n("mgr", "Manager Approval", "type: decision", "decision", "approve / reject / escalate"),
    n("mgr_reject", "Stop: Rejected", "type: end", "terminal", "manager rejected request"),
    n("mgr_escalate", "Escalate to HR", "type: end", "terminal", "manager timeout/escalation"),
    n("bg", "Background Check", "type: collector", "human"),
    n("provision", "Provision Resources", "type: parallel", "control", "okta/github/slack/laptop/it-call"),
    n("okta", "Create Okta User", "type: tool", "automation"),
    n("gh", "Invite GitHub", "type: tool", "automation"),
    n("slack", "Invite Slack", "type: tool", "automation"),
    n("laptop", "Order Laptop", "type: collector", "human"),
    n("join", "Join", "parallel join", "control"),
    n("close", "Close Ticket", "type: tool/cli", "automation"),
    n("end", "End", "type: end", "terminal"),
  ],
  edges: [
    e("o1", "collect", "mgr"),
    e("o2", "mgr", "bg", "approved"),
    e("o2b", "mgr", "mgr_reject", "rejected"),
    e("o2c", "mgr", "mgr_escalate", "escalated"),
    e("o3", "bg", "provision"),
    e("o4", "provision", "okta", "branch"),
    e("o5", "provision", "gh", "branch"),
    e("o6", "provision", "slack", "branch"),
    e("o7", "provision", "laptop", "branch"),
    e("o8", "okta", "join"),
    e("o9", "gh", "join"),
    e("o10", "slack", "join"),
    e("o11", "laptop", "join"),
    e("o12", "join", "close"),
    e("o13", "close", "end"),
  ],
});

const canaryDeploy = buildScenario({
  id: "canary-deploy",
  name: "Canary Deploy + Compensation",
  archetype: "mitigation",
  summary:
    "Strong control-flow specimen: explicit decision routing, compensation registration, parallel deploy, iterate monitor loop, and promote/rollback branch.",
  nodes: [
    n("assert", "Pre-Deploy Assertions", "type: assert", "control"),
    n("approve", "Release Approval", "type: decision", "decision", "approve / reject / rollback"),
    n("approve_reject", "Stop: Release Rejected", "type: end", "terminal", "release manager rejected"),
    n("approve_escalate", "Escalate to Release Director", "type: end", "terminal", "approval timed out/escalated"),
    n("comp", "Register Rollback", "type: compensate", "compensation"),
    n("deploy", "Deploy Canary", "type: parallel", "control"),
    n("wait", "Wait Healthy", "type: cli + retry", "automation"),
    n("monitor", "Monitor Metrics Loop", "type: iterate", "control", "prometheus every 10s"),
    n("decision", "Promote or Rollback", "type: branch", "control"),
    n("promote", "Promote to 100%", "type: cli/tool", "automation"),
    n("rollback", "Execute Compensation", "on failure", "compensation"),
    n("end", "End", "type: end", "terminal"),
  ],
  edges: [
    e("c1", "assert", "approve"),
    e("c2", "approve", "comp", "approved"),
    e("c2b", "approve", "approve_reject", "rejected"),
    e("c2c", "approve", "approve_escalate", "escalated"),
    e("c3", "comp", "deploy"),
    e("c4", "deploy", "wait"),
    e("c5", "wait", "monitor"),
    e("c6", "monitor", "monitor", "next iteration", true),
    e("c7", "monitor", "decision"),
    e("c8", "decision", "promote", "healthy"),
    e("c9", "decision", "rollback", "unhealthy"),
    e("c10", "promote", "end"),
    e("c11", "rollback", "end"),
  ],
});

const compliance = buildScenario({
  id: "soc2-evidence",
  name: "SOC2 Evidence Collection",
  archetype: "reference",
  summary:
    "Inclusion-heavy compliance archetype with repeated include patterns, explicit attestation routing, and final packaging/upload path.",
  nodes: [
    n("init", "Initialize Audit Package", "type: cli", "automation"),
    n("include1", "Collect CC1.x", "type: include", "automation"),
    n("include2", "Collect CC3/4/5", "type: include", "automation"),
    n("include3", "Collect CC6 Bundle", "type: include", "automation"),
    n("manual", "Manual Evidence", "type: collector", "human", "risk assessment upload"),
    n("aggregate", "Aggregate Evidence", "type: cli", "automation"),
    n("report", "Generate Report", "type: extension", "automation"),
    n("officer1", "Compliance Attestation", "type: decision", "decision", "attest / reject / escalate"),
    n("officer1_reject", "Stop: Compliance Rejected", "type: end", "terminal", "compliance officer rejected package"),
    n("officer1_escalate", "Escalate to CISO", "type: end", "terminal", "compliance escalation path"),
    n("officer2", "Security Attestation", "type: decision", "decision", "attest / reject / escalate"),
    n("officer2_reject", "Stop: Security Rejected", "type: end", "terminal", "security officer rejected package"),
    n("officer2_escalate", "Escalate to CISO", "type: end", "terminal", "security escalation path"),
    n("vault", "Upload to Vault", "type: cli", "automation"),
    n("end", "End", "type: end", "terminal"),
  ],
  edges: [
    e("s1", "init", "include1"),
    e("s2", "include1", "include2"),
    e("s3", "include2", "include3"),
    e("s4", "include3", "manual"),
    e("s5", "manual", "aggregate"),
    e("s6", "aggregate", "report"),
    e("s7", "report", "officer1"),
    e("s8", "officer1", "officer2", "attested"),
    e("s8b", "officer1", "officer1_reject", "rejected"),
    e("s8c", "officer1", "officer1_escalate", "escalated"),
    e("s9", "officer2", "vault", "attested"),
    e("s9b", "officer2", "officer2_reject", "rejected"),
    e("s9c", "officer2", "officer2_escalate", "escalated"),
    e("s10", "vault", "end"),
  ],
});

const securityBreach = buildScenario({
  id: "security-breach",
  name: "Security Breach Containment",
  archetype: "mitigation",
  summary:
    "Severity triage routes into different containment depths, then converges into forensics and stakeholder notification.",
  nodes: [
    n("alert", "Receive SIEM Alert", "type: wait_for_event", "trigger"),
    n("triage", "Severity Triage", "type: decision", "decision", "critical / high / medium / low"),
    n("contain_full", "Full Containment", "type: parallel", "control", "isolate systems in parallel"),
    n("revoke", "Revoke Credentials", "type: parallel", "control", "aws/okta/internal-api"),
    n("contain_targeted", "Targeted Containment", "type: tool", "automation"),
    n("investigate", "Investigate Suspicious Activity", "type: tool", "automation"),
    n("forensics", "Collect Forensics", "type: tool/extension", "automation"),
    n("notify", "Notify Stakeholders", "type: tool", "automation"),
    n("close_low", "Close as Low Severity", "type: end", "terminal"),
    n("end", "Incident Managed", "type: end", "terminal"),
  ],
  edges: [
    e("sb1", "alert", "triage"),
    e("sb2", "triage", "contain_full", "critical"),
    e("sb3", "triage", "contain_targeted", "high"),
    e("sb4", "triage", "investigate", "medium"),
    e("sb5", "triage", "close_low", "low"),
    e("sb6", "contain_full", "revoke"),
    e("sb7", "revoke", "forensics"),
    e("sb8", "contain_targeted", "forensics"),
    e("sb9", "investigate", "notify"),
    e("sb10", "forensics", "notify"),
    e("sb11", "notify", "end"),
  ],
});

const dbMigration = buildScenario({
  id: "database-migration",
  name: "Database Migration",
  archetype: "reference",
  summary:
    "Preflight checks and dry-run converge into DBA approval decision, then production migration with rollback registration.",
  nodes: [
    n("preflight", "Pre-Flight Checks", "type: assert", "control"),
    n("dryrun", "Dry-Run on Staging", "type: cli", "automation"),
    n("validate_staging", "Validate Staging", "type: cli", "automation"),
    n("estimate", "Estimate Duration", "type: cli", "automation"),
    n("dba", "DBA Approval", "type: decision", "decision", "approved / rejected / escalated"),
    n("schedule", "Schedule Maintenance", "type: collector", "human"),
    n("snapshot", "Take Snapshot", "type: cli", "automation"),
    n("rollback", "Register Rollback", "type: compensate", "compensation"),
    n("execute", "Execute Migration", "type: cli", "automation"),
    n("validate_prod", "Validate Production", "type: cli", "automation"),
    n("reject", "Stop: Migration Rejected", "type: end", "terminal"),
    n("escalate", "Escalate to DBA Lead", "type: end", "terminal"),
    n("end", "Migration Complete", "type: end", "terminal"),
  ],
  edges: [
    e("db1", "preflight", "dryrun"),
    e("db2", "dryrun", "validate_staging"),
    e("db3", "validate_staging", "estimate"),
    e("db4", "estimate", "dba"),
    e("db5", "dba", "schedule", "approved"),
    e("db6", "dba", "reject", "rejected"),
    e("db7", "dba", "escalate", "escalated"),
    e("db8", "schedule", "snapshot"),
    e("db9", "snapshot", "rollback"),
    e("db10", "rollback", "execute"),
    e("db11", "execute", "validate_prod"),
    e("db12", "validate_prod", "end"),
  ],
});

const financialApproval = buildScenario({
  id: "financial-approval",
  name: "Financial Approval Ladder",
  archetype: "reference",
  summary:
    "Multi-level approval decisions route by amount tier before final procurement execution.",
  nodes: [
    n("request", "Purchase Request Form", "type: collector", "human"),
    n("manager", "Manager Approval", "type: decision", "decision", "approved / rejected / escalated"),
    n("finance", "Finance Approval", "type: decision", "decision", "approved / rejected / escalated"),
    n("tier", "Route by Amount Tier", "type: branch", "control"),
    n("director", "Director Approval", "type: decision", "decision"),
    n("vp", "VP Approval", "type: decision", "decision"),
    n("cfo", "CFO Approval", "type: decision", "decision"),
    n("procure", "Issue Purchase Order", "type: extension/tool", "automation"),
    n("reject", "Stop: Request Rejected", "type: end", "terminal"),
    n("escalate", "Escalate to Executive", "type: end", "terminal"),
    n("end", "Approval Complete", "type: end", "terminal"),
  ],
  edges: [
    e("fa1", "request", "manager"),
    e("fa2", "manager", "finance", "approved"),
    e("fa3", "manager", "reject", "rejected"),
    e("fa4", "manager", "escalate", "escalated"),
    e("fa5", "finance", "tier", "approved"),
    e("fa6", "finance", "reject", "rejected"),
    e("fa7", "finance", "escalate", "escalated"),
    e("fa8", "tier", "director", "50k-100k"),
    e("fa9", "tier", "vp", "100k-500k"),
    e("fa10", "tier", "cfo", ">=500k"),
    e("fa11", "director", "procure", "approved"),
    e("fa12", "director", "reject", "rejected"),
    e("fa13", "vp", "procure", "approved"),
    e("fa14", "vp", "reject", "rejected"),
    e("fa15", "cfo", "procure", "approved"),
    e("fa16", "cfo", "reject", "rejected"),
    e("fa17", "procure", "end"),
  ],
});

const fdaRelease = buildScenario({
  id: "fda-release",
  name: "FDA Device Release",
  archetype: "reference",
  summary:
    "Regulated release pipeline with sequential attestations and regulatory submission decision routing.",
  nodes: [
    n("qa", "QA Attestation", "type: decision", "decision", "attest / reject / escalate"),
    n("risk", "Risk Attestation", "type: decision", "decision", "attest / reject / escalate"),
    n("clinical", "Clinical Validation", "type: collector", "human"),
    n("cyber", "Cybersecurity Attestation", "type: decision", "decision", "attest / reject / escalate"),
    n("reg", "Submission Type Decision", "type: decision", "decision", "no submission / LTF / 510k"),
    n("no_submit", "No Submission Path", "type: cli", "automation"),
    n("ltf", "Letter to File Path", "type: extension", "automation"),
    n("k510", "Special 510(k) Path", "type: collector", "human"),
    n("reject", "Stop: Review Rejected", "type: end", "terminal"),
    n("escalate", "Escalate to Regulatory Lead", "type: end", "terminal"),
    n("manufacturing", "Manufacturing Release", "type: decision", "decision", "approved / rejected"),
    n("end", "Release Complete", "type: end", "terminal"),
  ],
  edges: [
    e("fd1", "qa", "risk", "attested"),
    e("fd2", "qa", "reject", "rejected"),
    e("fd3", "qa", "escalate", "escalated"),
    e("fd4", "risk", "clinical", "attested"),
    e("fd5", "risk", "reject", "rejected"),
    e("fd6", "risk", "escalate", "escalated"),
    e("fd7", "clinical", "cyber"),
    e("fd8", "cyber", "reg", "attested"),
    e("fd9", "cyber", "reject", "rejected"),
    e("fd10", "cyber", "escalate", "escalated"),
    e("fd11", "reg", "no_submit", "no submission"),
    e("fd12", "reg", "ltf", "letter to file"),
    e("fd13", "reg", "k510", "special 510(k)"),
    e("fd14", "no_submit", "manufacturing"),
    e("fd15", "ltf", "manufacturing"),
    e("fd16", "k510", "manufacturing"),
    e("fd17", "manufacturing", "end", "approved"),
    e("fd18", "manufacturing", "reject", "rejected"),
  ],
});

const oncallEscalation = buildScenario({
  id: "oncall-escalation",
  name: "On-Call Escalation Ladder",
  archetype: "mitigation",
  summary:
    "Iterative paging escalates through responder tiers until acknowledgment decision resolves or triggers broadcast.",
  nodes: [
    n("alert", "Receive Critical Alert", "type: extension/wait", "trigger"),
    n("lookup", "Lookup On-Call Schedule", "type: extension", "automation"),
    n("primary", "Try Primary (iterate)", "type: iterate", "control"),
    n("ack1", "Acknowledged?", "type: decision", "decision", "yes / no"),
    n("secondary", "Try Secondary (iterate)", "type: iterate", "control"),
    n("ack2", "Acknowledged?", "type: decision", "decision", "yes / no"),
    n("manager", "Try Manager (iterate)", "type: iterate", "control"),
    n("ack3", "Acknowledged?", "type: decision", "decision", "yes / no"),
    n("director", "Try Director (iterate)", "type: iterate", "control"),
    n("ack4", "Acknowledged?", "type: decision", "decision", "yes / no"),
    n("broadcast", "Broadcast + Executive Escalation", "type: extension", "automation"),
    n("resolved", "Incident Acknowledged", "type: end", "terminal"),
    n("end", "Escalation Exhausted", "type: end", "terminal"),
  ],
  edges: [
    e("oc1", "alert", "lookup"),
    e("oc2", "lookup", "primary"),
    e("oc3", "primary", "ack1"),
    e("oc4", "ack1", "resolved", "yes"),
    e("oc5", "ack1", "secondary", "no"),
    e("oc6", "secondary", "ack2"),
    e("oc7", "ack2", "resolved", "yes"),
    e("oc8", "ack2", "manager", "no"),
    e("oc9", "manager", "ack3"),
    e("oc10", "ack3", "resolved", "yes"),
    e("oc11", "ack3", "director", "no"),
    e("oc12", "director", "ack4"),
    e("oc13", "ack4", "resolved", "yes"),
    e("oc14", "ack4", "broadcast", "no"),
    e("oc15", "broadcast", "end"),
  ],
});

const gdprDeletion = buildScenario({
  id: "gdpr-deletion",
  name: "GDPR Data Deletion",
  archetype: "reference",
  summary:
    "Identity and legal approvals route into parallel discovery and deletion, then DPO sign-off and certificate generation.",
  nodes: [
    n("receive", "Receive Deletion Request", "type: extension", "trigger"),
    n("identity", "Identity Verification", "type: decision", "decision", "verified / rejected / timeout"),
    n("legal", "Legal Review", "type: decision", "decision", "approved / rejected / hold"),
    n("search", "Search Data Stores", "type: parallel", "control"),
    n("dpo", "DPO Scope Confirmation", "type: decision", "decision", "confirm / reject / escalate"),
    n("delete", "Delete Across Systems", "type: parallel", "control", "best-effort deletion"),
    n("verify", "Verify Deletion", "type: assert", "control"),
    n("certificate", "Generate Deletion Certificate", "type: extension", "automation"),
    n("reject", "Stop: Request Rejected", "type: end", "terminal"),
    n("hold", "Stop: Legal Hold", "type: end", "terminal"),
    n("escalate", "Escalate to Privacy Lead", "type: end", "terminal"),
    n("end", "Deletion Complete", "type: end", "terminal"),
  ],
  edges: [
    e("gd1", "receive", "identity"),
    e("gd2", "identity", "legal", "verified"),
    e("gd3", "identity", "reject", "rejected"),
    e("gd4", "identity", "escalate", "timeout"),
    e("gd5", "legal", "search", "approved"),
    e("gd6", "legal", "reject", "rejected"),
    e("gd7", "legal", "hold", "legal hold"),
    e("gd8", "search", "dpo"),
    e("gd9", "dpo", "delete", "confirmed"),
    e("gd10", "dpo", "reject", "rejected"),
    e("gd11", "dpo", "escalate", "escalated"),
    e("gd12", "delete", "verify"),
    e("gd13", "verify", "certificate"),
    e("gd14", "certificate", "end"),
  ],
});

export const scenarios: FlowScenario[] = [
  k8sIncident,
  canaryDeploy,
  onboarding,
  compliance,
  securityBreach,
  dbMigration,
  financialApproval,
  fdaRelease,
  oncallEscalation,
  gdprDeletion,
];
